# Generated by Django 6.0.1 on 2026-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
