# Generated by Django 6.0.1 on 2026-02-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_core', '0002_fooditem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('break_slot', models.CharField(choices=[('SHORT', 'Short Break'), ('LUNCH', 'Lunch'), ('EVENING', 'Evening Break')], default='LUNCH', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('items', models.JSONField(default=list)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
