# Generated by Django 6.0.1 on 2026-02-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_core', '0003_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(upload_to='student_faces/')),
                ('face_encoding', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='campus_core.studentprofile')),
            ],
        ),
    ]
